name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.6.0"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Create Frontend .env
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_VITE_API: ${{ secrets.VITE_API }}
          envkey_VITE_VERSION: ${npm_package_version}
          directory: apps/frontend/

      - name: Create Backend .env
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_DATABASE: ${{ secrets.DATABASE }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_PORT: ${{ secrets.PORT }}
          envkey_APP_URL: ${{ secrets.APP_URL }}
          envkey_IS_DEV: ${{ secrets.IS_DEV }}
          envkey_EMAIL_SMTP: ${{ secrets.EMAIL_SMTP }}
          envkey_EMAIL_USER: ${{ secrets.EMAIL_USER }}
          envkey_EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          directory: apps/backend/

      - name: Build
        run: npm run build

      - name: Lint check
        run: npm run lint
      - name: Type check
        run: npm run ts
      - name: Unit tests
        run: npm run test:cov